lib_app/urls.py
from django.contrib import admin
from django.urls import path
from .views import login,BookList,logout,search

app_name='lib_app'

urlpatterns = [
    path('login/',login,name='login'),
    path('booklist/',BookList.as_view(),name='booklist'),
    path('logout',logout,name='logout'),
    path('search/',search,name='search')
]

library/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',register,name="register"),
    path('lib/',include('lib_app.urls'))
]

lib_app/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass


class Author(models.Model):
    name=models.CharField(max_length=200)

    def __str__(self,*args,**kwargs):
        return self.name


class Category(models.Model):
    name=models.CharField(max_length=200)

    def __str__(self,*args,**kwargs):
        return self.name


class Book(models.Model):
 title=models.CharField(max_length=200)
 author=models.ManyToManyField(Author,through='Publication',related_name='auth_book')
 cat=models.ForeignKey(Category,on_delete=models.SET_NULL,null=True,related_name='cat_book')
 slug_title=models.SlugField(blank=True,allow_unicode=True)

 def save(self, *args,**kwargs) -> None:
    if not self.slug_title:
        self.slug_title=slugify(self.title,allow_unicode=True)
    super().save(*args,**kwargs)

 def __str__(self,*args,**kwargs):
        return self.title


class Publication(models.Model):
    book=models.ForeignKey(Book,on_delete=models.CASCADE,related_name='book_pub')
    author=models.ForeignKey(Author,on_delete=models.CASCADE,related_name='auth_pub')
    pub_name=models.CharField(max_length=200)
    pub_date=models.IntegerField()
    img=models.ImageField(upload_to='book_img/',null=True,blank=True)
    user=models.ManyToManyField(User,through='Loan',related_name='user_pub')

    class Meta:
        ordering=['pub_date']

    def __str__(self,*args,**kwargs):
        return f"{self.book}:{self.pub_name}"


class Loan(models.Model):
    user=models.ForeignKey(User,on_delete=models.DO_NOTHING,related_name='user_loan')
    book=models.ForeignKey(Publication,on_delete=models.DO_NOTHING,related_name='book_loan')
    loan_date=models.DateField()
    return_date=models.DateField()
    desc=models.TextField(null=True,blank=True)

    def __str__(self,*args,**kwargs):
        return f"{self.user}:{self.book}"

lib_app/forms.py
from dataclasses import field
from .models import User,Book
from django import forms



class LoginForm(forms.Form):
    username=forms.CharField(max_length=200)
    password=forms.CharField(max_length=200)
    

class SearchForm(forms.Form):
    book=forms.CharField(max_length=200,required=False)
    author=forms.CharField(max_length=200,required=False)
    cat=forms.CharField(max_length=200,required=False)

   



    

library/forms.py
from lib_app.models import User
from django.forms import ModelForm
from django.contrib.auth.hashers import make_password


class RegisterForm(ModelForm):
    class Meta:
        model=User
        fields=['username','password']

    def save(self,commit=True,*args,**kwargs):# Active Users After Register and Hash They Passwords
        self.instance.is_active=True
        self.instance.is_staff=True
        self.instance.password=make_password(self.cleaned_data.get('password'))
        return super().save(commit,*args,**kwargs)

lib_app/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView
from .forms import LoginForm,SearchForm
from .models import Book,Publication
from django.contrib.auth import login as _login, authenticate,logout as _logout


def login(request):# Login Registered Users Or Get Errors For Unregistered Users
    error=''
    if request.method=='GET':
        form=LoginForm()
        return render(request,'lib_app/login.html',{'form':form})
    else:
        form=LoginForm(request.POST)
        if form.is_valid():
            _username=form.cleaned_data.get('username','')
            _password=form.cleaned_data.get('password','')
            user=authenticate(request,username=_username,password=_password)
            if user:
                _login(request,user)
                return redirect('lib_app:booklist')
            else:
                error='Please Enter Username and Passwork Correctly Or Register First'
                return render(request,'lib_app/login.html',{'form':form,'error':error})
        else:
            error=form.errors
            return render(request,'lib_app/login.html',{'form':form,'error':error})
                

class BookList(ListView):# List All Books With Some Attributes
    model=Publication
    template_name='lib_app/booklist.html'
    context_object_name='books'
    paginate_by=12
    
        
def logout(request):# Logout The Loggedin User
    form = LoginForm()
    context={"form":form,"msg":"you loged out"}
    _logout(request)
    return render(request,'lib_app/login.html',context)


def find(request,**kwargs):# Doing Filter By input Arguments Like Book title, Book Author Or Book Category
    _book=kwargs.get('book','')
    _author=kwargs.get('author','')
    _cat=kwargs.get('cat','')
    books=''
    error=''
    msg='please fill just  one filed'
    if not _book and not  _author and not  _cat: # If All 3 Fields Will Be Empty
        error=msg
    elif _book:
        if _author or _cat: # For Suring Just book Field IS Filled
            error=msg
        else:
            books=Publication.objects.filter(book__title__icontains=_book)
    elif _author:
        if _book or _cat:# For Suring Just author Field IS Filled
            error=msg
        else:
            books=Publication.objects.filter(author__name__icontains=_author)
    elif _cat:
        if _book or _author:# For Suring Just category Field IS Filled
            error=msg
        else:
            books=Book.objects.filter(cat__name__icontains=_cat)
    return {'books':books,'error':error}
       

def search(request):# Create Search Form and render the search.html and Using The find function
    if request.method=='GET':
        searchform=SearchForm()
        return render(request,'lib_app/search.html',{'searchform':searchform})
    else:
        searchform=SearchForm(request.POST)
        if searchform.is_valid():
            error=''
            books=''
            print(searchform.cleaned_data)
            _book=searchform.cleaned_data.get('book','')
            _author=searchform.cleaned_data.get('author','')
            _cat=searchform.cleaned_data.get('cat','')
            find_output=find(request,book=_book,author=_author,cat=_cat)
            books=find_output.get('books')
            error=find_output.get('error')
            print(f"boooooooooooks:{books}")
            return render(request,'lib_app/search.html',{'searchform':searchform,'books':books,'error':error})
        else:
            error=searchform.errors
            return render(request,'lib_app/search.html',{'searchform':searchform,'error':error})

library/views.py
from django.shortcuts import render
from .forms import RegisterForm
from lib_app.models import User


def register(request):
    context={}
    if request.method=='POST':
            form=RegisterForm(request.POST)
            if form.is_valid():
                _username=form.cleaned_data.get('username','')
                if User.objects.filter(username=_username).exists():
                    return render(request,'index.html',{"msg":"username already exist"})
                else:
                    form.save()
                    
                    return render(request,'index.html',{"form":form,"msg":"user created sucessfully Now you should login"})
            else:
                return render(request,'index.html',{"form":form,"msg":form.errors})
    else:
        form=RegisterForm()
        context['form']=form
        return render(request,'index.html',context)
    

lib_app/templates/lib_app/booklist.html
{% extends "index.html" %}
<!DOCTYPE html>
<html lang="en">
{% block body %}
<h2>Book List:</h2>
<table border = "1" width="50%">
         <tr>
            <th>Book</th>
            <th>Author</th>
            <th>Publication</th>
         </tr>
    {% for book in books %}
         <tr>
            <td>{{book.book}}</td>
            <td>{{book.author}}</td>
            <td>{{book.pub_name}}</td>
         </tr>
    {% endfor %}
</table>
{% endblock body %}

</html>

lib_app/templates/lib_app/login.html
{% extends "index.html" %}
<!DOCTYPE html>
<html lang="en">

{% block body %}

    <form action="{%url 'lib_app:login' %}" , method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="login">
    </form>
    <p>{{error}}</p>

{% endblock body %}

</html> 

lib_app/templates/lib_app/search.html
{% extends "index.html" %}
<!DOCTYPE html>
<html lang="en">

{% block body %}
<h2>search books by:</h2>
    <form action="{%url 'lib_app:search' %}" , method="post">
        {% csrf_token %}
        {{searchform.as_p}}
        <input type="submit" value="search">
    </form>
    <h3>{{error}}</h3>
    <p></p>
    <p></p>
    <table border = "1" width="50%">
         <tr>
            <th>Book</th>
            <th>Author</th>
            <th>Publication</th>
         </tr>
    {%for elm in books  %}
    {% if elm.title %}
    <tr><td>{{elm.title}}</td>
    <td></td>
    <td></td>
    </tr>
    {% else %}
    {% comment %} <li>{{elm.book_pub.pub_name}} {% endcomment %}
     <tr>
        <td>{{elm.book}}</td>
        <td>{{elm.author}}</td>
        <td>{{elm.pub_name}}</td>
    </tr>
    {% endif %}
    {% endfor %}
    </table>
{% endblock body %}

</html> 

templates/header.html
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% if not user.is_authenticated %}
    <h2>To See The Book List Please Login First</h2>
    {% endif %}

    <style>ul {  list-style-type: none;} li{display: inline-block;padding:20px;} a{text-decoration: none; color: blueviolet;}</style>
     <ul>
            {% if user.is_authenticated %}
            <li>Hi  {{user.username}}!  Welcome!</li>
                <li> <a href="{% url 'lib_app:booklist'%}">books</a> </li>
                <li> <a href="{% url 'lib_app:search'%}">search</a> </li> 
                <li><a href="{% url 'lib_app:logout' %}">logout</a></li>
            {% else %}
                <li><a href="{% url 'lib_app:login' %}">login</a></li>
                <li><a href="{% url 'register' %}">register</a></li>
            {% endif %}
     </ul>
</head>

templates/index.html
<!DOCTYPE html>
<html lang="en">
{% block header %}
{% include "header.html" %}
{% endblock header %}
{% block body %}
<body>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
  </form>
  {{msg}}
</body>
{% endblock body %}
</html>